export { default as Home } from './Home';
export { default as Discover } from './Discover';
export { default as Library } from './Library';
export { default as Upload } from './Upload';
export { default as Profile } from './Profile';
export { default as Dashboard } from './Dashboard';
export { default as Activity } from './Activity';
export { default as Following } from './Following';
export { default as Settings } from './Settings'; 